### ISSUE TITLE
Parse error on some incoming Heroku log entries?

### ISSUE THREAD

**Issue by danielmcquillen** [deepsyx/node-heroku-cloudwatch-drain#2]
Thanks for great library. Gave it a spin today on a test app I've posted to Heroku. Worked pretty well, but getting an occasional error from the parseMetrics module:

```
TypeError: line.match is not a function or its return value is not iterable
    at Object.parseMemoryMetrics (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/node-heroku-cloudwatch-drain/src/parseMetrics.js:16:11)
    at /home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/node-heroku-cloudwatch-drain/src/index.js:47:16
    at messages.forEach.message (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/node-heroku-cloudwatch-drain/src/setupExpress.js:31:32)
    at Array.forEach (<anonymous>)
    at /home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/node-heroku-cloudwatch-drain/src/setupExpress.js:31:13
    at Layer.handle [as handle_request] (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/node-heroku-cloudwatch-drain/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/node-heroku-cloudwatch-drain/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/node-heroku-cloudwatch-drain/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/node-heroku-cloudwatch-drain/node_modules/express/lib/router/layer.js:95:5)
    at /home/ubuntu/.nvm/versions/node/v8.11.4/lib/node_modules/node-heroku-cloudwatch-drain/node_modules/express/lib/router/index.js:281:22
```

**Comment by deepsyx** [comment]
@danielmcquillen Hello. Sorry for the delayed response, but seems I missed that notification. We made a fix for this, but need to wait few more days to make sure everything works smoothly. Will deploy the new version, when we verify it :)

**Comment by abrkn** [comment]
@deepsyx Any update on this?
